### ISSUE TITLE
bypassing PCRD jailbreak verification on iOS 12.3.1 and 12.5.3 

### ISSUE THREAD

**Issue by krulci** [NyaMisty/KernInfra#1]
Hello, I read your repo about bypassing jailbreak verification with KernBypass for PCRD. My devices are on iOS 12.3.1 and 12.5.3. Since Apple stop signing 14.3 for update, is there any other option to bypass the jailbreak verification with PCRD on either of these iOS versions?

**Comment by NyaMisty** [comment]
Use old version KernBypass instead

krulci ***@***.***>于2021年6月1日 周二09:40写道：

**Comment by krulci** [comment]
Yes. I am using the original KernBypass from https://cydia.ichitaso.com
When ever I open PCRD, it jumps to MAIL app.

**Comment by NyaMisty** [comment]
Well you should look at my old KernBypass
ichitaso didn't correcly configured my fork

**Comment by krulci** [comment]
I have just tried your KernBypass from "http://repo.misty.moe/apt"
I did 
changerootfs &
disown %1
I was exited after about 30 seconds at black screen.

**Comment by krulci** [comment]
@NyaMisty 
Just an update. For iOS 12.5.3, I am unable to do the following:
`mksparsedmg /var/mobile/kernbypass_asset/kernbypass.dmg`
Therefore, none of the following steps could continue. Please let me know if there is any other method to complete this step.

For the purpose of this, I bought a brand new iPhone 7 Plus and jailbroke it with checkra1n 0.12.2 on iOS 14.4.1.
I followed the steps in "http://repo.misty.moe/" with an addition of installing `libkrw.0.dylib` from `apt.bingner.com`
I successfully opened the game.
